http://localhost:5203/api/routes/ping?secure=true&token=valid-token&input=Test123`

###
GET http://localhost:5203/download

###
GET http://localhost:5203/time

###
GET http://localhost:5203/greet/Samuel

### 
PUT http://localhost:5203/
###
DELETE http://localhost:5203/delete
###
POST http://localhost:5203/
